Add hhfab vlab setup-vpcs helper
githedgehog/docs pull request #38
Opened 2024-08-15 12:05 UTC by sergeymatov

2024-08-15 17:09 UTC, Frostman requested changes

2024-08-15 17:09 UTC, Frostman commented on docs/vlab/demo.md
> +> **_NOTE_** Make usre that route table on servers is properly configured if you setting up interfaces manually.
typo: usre -> sure and can you describe potentially most popular problem about default routes

2024-08-15 17:09 UTC, Frostman commented on docs/vlab/demo.md
> +In this example 10 VPC has been created for 10 servers. Subnets was autogenerated based on Ipv4namespace base CIDR. All servers get attachments based on Connections (mc-lag, es-lag, unbundled, etc).
let's use spelling from our API: IPv4Namespace, MCLAG, ESLAG

2024-08-15 17:09 UTC, Frostman commented on docs/vlab/running.md
> +> **_NOTE:_** SONiC system bootstrap may take reasonable time. It's heavily rely on the host disk and CPU performance, and parallel VM setup
it heavily relies on

2024-08-15 17:24 UTC, Frostman requested changes

2024-08-15 17:24 UTC, Frostman commented on docs/vlab/demo.md
> +> **_NOTE_** Make sure that route table on servers is properly configured if you setting up interfaces manually.
Could you please describe here what is "properly configured" means

2024-08-15 19:37 UTC, mrbojangles3 commented on docs/vlab/demo.md
> +In this example 10 VPC has been created for 10 servers. Subnets was autogenerated based on Ipv4namespace base CIDR. All servers get attachments based on Connections (mc-lag, es-lag, unbundled, etc).
Grammar nits:
"10 VPCs have been created" 
"Subnets have been auto generated"
"All servers are assigned attachments"

2024-08-15 19:43 UTC, mrbojangles3 requested changes
Minor Grammar Nits attached to Sergei's comments

2024-08-16 06:51 UTC, sergeymatov commented on docs/vlab/demo.md
> +In this example 10 VPC has been created for 10 servers. Subnets was autogenerated based on Ipv4namespace base CIDR. All servers get attachments based on Connections (mc-lag, es-lag, unbundled, etc).
done

2024-08-16 14:36 UTC, mrbojangles3 approved these changes

2024-10-24 19:20 UTC, closed without merging